apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-tls
  namespace: tendersbay-xyz
spec:
  secretName: platform-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: tendersbay.xyz
  dnsNames:
    - tendersbay.xyz
    - www.tendersbay.xyz
