root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/platform ."
bin = "./tmp/platform"
include_ext = ["go"]
exclude_dir = ["tmp", "dist", "bin", "node_modules"]
delay = 200

[log]
time = true
